import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen flex flex-col font-inter">
        <div className="w-full h-50 flex justify-center items-center bg-black">
          <div className="flex items-center gap-2">
            <img width={22} src="/logo.svg" alt="Logo" />
            <span className="font-inter font-black text-4.5xl text-todo">Todo</span>
            <span className="font-inter font-black text-4.5xl text-check">App</span>
          </div>
        </div>
        <div className="w-full grow shrink bg-grey">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
